# -*- coding: utf-8 -*-
"""Redact.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19yCT_Zv6xW2wd1svCvOBPn7HR8uPf9-Q
"""

!pip install Faker python-docx spacy spacy-transformers
!python -m spacy download en_core_web_trf

!python -m spacy download en_core_web_trf

import re
import spacy
from faker import Faker
from docx import Document

fake = Faker('en_IN')

try:
    nlp = spacy.load('en_core_web_trf')
except OSError:
    import spacy.cli
    spacy.cli.download('en_core_web_trf')
    nlp = spacy.load('en_core_web_trf')

if 'entity_ruler' not in nlp.pipe_names:
    ruler = nlp.add_pipe('entity_ruler', before='ner')
    address_patterns = [
        {'label': 'GPE', 'pattern': [{'LOWER': 'gat'}, {'LOWER': 'no'}]},
        {'label': 'GPE', 'pattern': [{'LOWER': 'village'}]},
        {'label': 'GPE', 'pattern': [{'LOWER': 'taluka'}]},
        {'label': 'GPE', 'pattern': [{'LOWER': 'khed'}]},
        {'label': 'GPE', 'pattern': [{'LOWER': 'chakan'}]},
        {'label': 'GPE', 'pattern': [{'LOWER': 'birdewadi'}]},
        {'label': 'GPE', 'pattern': [{'TEXT': {'REGEX': r'\d{1,3}/\d{1,3}'}}]}
    ]
    ruler.add_patterns(address_patterns)

class ProductionPIIRedactorV6:
    def __init__(self):
        self.pii_map = {}
        self.extracted_entities = set()

        self.patterns = {
            'EMAIL': r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}',
            'PHONE': r'\+\s?\d{1,4}(?:\s?\d{1,5}){2,5}',
            'SSN': r'\b\d{3}-\d{2}-\d{4}\b',
            'CREDIT_CARD': r'\b(?:\d[ -]*?){13,16}\b',
            'IP_ADDRESS': r'\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b',
            'DOB': r'\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b'
        }

        self.protected_entities = {
            'Securities and Exchange Board of India': '___PROT_SEBI___',
            'National Stock Exchange of India Limited': '___PROT_NSE___',
            'BSE Limited': '___PROT_BSE___',
            'Registrar of Companies': '___PROT_ROC___',
            'Companies Act, 2013': '___PROT_COMPACT___'
        }
        self.reverse_protected = {v: k for k, v in self.protected_entities.items()}

        self.exclusion_terms = {
            'offer', 'issue', 'qib', 'nii', 'rii', 'fpi', 'fema', 'equity',
            'share', 'shares', 'shareholder', 'prospectus', 'red herring', 'sebi',
            'icdr', 'bse', 'nse', 'working day', 'price band', 'face value', 'promoter',
            'director', 'board', 'rupee', 'rupees', 'million', 'billion', 'company',
            'act', 'regulation', 'market', 'exchange', 'ipo', 'corporate', 'office',
            'statement', 'revenue', 'tax', 'profit', 'margin', 'capital', 'asset',
            'liability', 'customer', 'supplier', 'capacity', 'utilization', 'statutory',
            'auditor', 'legal', 'policy', 'committee', 'chairman', 'officer', 'employee',
            'pat', 'gaap', 'ebitda', 'roc', 'trade', 'portion', 'bidders', 'bidding'
        }

    def is_false_positive(self, text):
        clean_text = text.lower().strip()
        if text.isupper() and 2 <= len(text.replace(' ', '')) <= 5:
            return True
        words = set(re.sub(r'[^\w\s]', '', clean_text).split())
        if words.intersection(self.exclusion_terms):
            return True
        return len(text.strip()) <= 2

    def get_fake_value(self, original_text, pii_type):
        self.extracted_entities.add(original_text.strip())
        if original_text in self.pii_map:
            return self.pii_map[original_text]

        if pii_type == 'EMAIL':
            fake_val = fake.ascii_safe_email()
        elif pii_type == 'PHONE':
            fake_val = fake.phone_number()
        elif pii_type == 'DOB':
            fake_val = fake.date_of_birth().strftime('%d/%m/%Y')
        elif pii_type == 'PERSON':
            fake_val = fake.name()
        elif pii_type == 'ORG':
            fake_val = fake.company()
        elif pii_type in ['GPE', 'LOC']:
            fake_val = fake.city()
        else:
            fake_val = '[REDACTED]'

        self.pii_map[original_text] = fake_val
        return fake_val

    def redact_text(self, text):
        if not text.strip():
            return text

        for regular_phrase, secure_token in self.protected_entities.items():
            text = re.sub(re.escape(regular_phrase), secure_token, text, flags=re.IGNORECASE)

        for pii_type, pattern in self.patterns.items():
            text = re.sub(pattern, lambda m: self.get_fake_value(m.group(), pii_type), text, flags=re.IGNORECASE)

        doc = nlp(text)
        for ent in reversed(doc.ents):
            if ent.label_ in ['PERSON', 'ORG', 'GPE', 'LOC']:
                if '___PROT_' in ent.text or self.is_false_positive(ent.text):
                    continue
                fake_text = self.get_fake_value(ent.text, ent.label_)
                text = text[:ent.start_char] + fake_text + text[ent.end_char:]

        for secure_token, regular_phrase in self.reverse_protected.items():
            text = text.replace(secure_token, regular_phrase)

        return text

    def redact_docx(self, input_path, output_path):
        doc = Document(input_path)
        for para in doc.paragraphs:
            para.text = self.redact_text(para.text)
        for table in doc.tables:
            for row in table.rows:
                for cell in row.cells:
                    cell.text = self.redact_text(cell.text)
        doc.save(output_path)

if __name__ == '__main__':
    redactor = ProductionPIIRedactorV6()
    input_file = '/content/Red Herring Prospectus.docx'
    output_file = '/content/Redacted_Red_Herring_Prospectus.docx'
    redactor.redact_docx(input_file, output_file)

